server:
  port: 8020
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 88888888
    url: jdbc:mysql://localhost:3306/pay
